### ISSUE TITLE
BUG: Spiel kann starten obwohl Spieler noch in der Cheatauswahl ist.

### ISSUE THREAD

**Issue by gery0815** [SE2-Busfahrer-SS20/SE2-Busfahrer-SS20#111]

**Comment by gery0815** [comment]
Spieler wird bereits beim drücken des Play Buttons in der Liste angezeigt und das Spiel kann gestartet werden, bevor der Spieler seinen Cheat ausgewählt hat. Das führ dazu, dass das Spiel beim diesem Spieler nicht gestartet wird. Wenn dieser Spieler dann dran ist, bleibt das Spiel hängen.

**Comment by mmaau** [comment]
Hab es versucht zu fixen, diese Variante hat vor paar Tagen bei Philipp, Larissa nicht funktioniert, bei mir hat es komischerweise schon funktioniert und funktioniert auch jetzt noch.  @gery0815 😄
