### ISSUE TITLE
[E02 - STORY 1] - Erstellen der Screens

### ISSUE THREAD

**Issue by Thunder1702** [SE2-Busfahrer-SS20/SE2-Busfahrer-SS20#14]
- Start Screen
- Main Menu
- New Player
- Edit Player
- Join Server
- Start Sever
- Cheats

**Comment by elsandner** [comment]
Der Screen für die erste Raterunde wurde bereits erstellt - siehe feature/E02-STORY06

**Comment by mmaau** [comment]
MainMenu
![Screenshot_1586865015](https://user-images.githubusercontent.com/46070797/79222280-895c3f00-7e57-11ea-9a3c-f3d9c201bb3f.png)
Start Server
![Screenshot_1586865027](https://user-images.githubusercontent.com/46070797/79222322-9b3de200-7e57-11ea-9667-d78549437861.png)
